/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class IntegrationSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'id', 'name', 'provider', 'slug', 'updatedAt'] as const
  $columns = IntegrationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare provider: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SourceRecordSchema extends BaseModel {
  static $columns = ['createdAt', 'externalId', 'id', 'payload', 'sourceUpdatedAt', 'syncRunId'] as const
  $columns = SourceRecordSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: any
  @column.dateTime()
  declare sourceUpdatedAt: DateTime | null
  @column()
  declare syncRunId: number
}

export class SyncRunSchema extends BaseModel {
  static $columns = ['createdAt', 'errorCode', 'errorMessage', 'finishedAt', 'id', 'integrationId', 'recordsFailed', 'recordsPersisted', 'recordsReceived', 'startedAt', 'status', 'updatedAt'] as const
  $columns = SyncRunSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorCode: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare integrationId: number
  @column()
  declare recordsFailed: number
  @column()
  declare recordsPersisted: number
  @column()
  declare recordsReceived: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
